export const SEND_PHONE_NUMBER = "SEND_PHONE_NUMBER";
export const SEND_VERIFY_CODE = "SEND_VERIFY_CODE";
export const SEND_LOGIN_DATA = "SEND_LOGIN_DATA";
export const SEND_TWO_REFERENCE_DATA = "SEND_TWO_REFERENCE_DATA";
export const SEND_CARRIER_DATA = "SEND_CARRIER_DATA";
